[project]

site_name = "Lumino Docs"

site_description = "All documentation of Lumino"

site_author = "Carla, Patricia y Jonay"

repo_url = "https://github.com/JonayKB/Lumino"

site_url = "https://jonaykb.github.io/Lumino/"

repo_name = "JonayKB/Lumino"

copyright = """
Copyright &copy; 2026 The Carla, Patricia y Jonay
"""

nav = [
  { "Inicio" = "index.md", "icon" = "lucide/home" },
  { "Guía de uso" = [
    "normal-users/index.md",
    { "Manual de usuario" = "normal-users/user-manual.md", "icon" = "lucide/book" },
    { "Solución de problemas" = "normal-users/troubleshooting.md", "icon" = "lucide/help-circle" },
    { "Preguntas frecuentes" = "normal-users/faq.md", "icon" = "lucide/message-circle" },
  ] },
  { "Guía técnica" = [
    "developers/index.md",
    { "Requisitos" = "developers/requirements.md", "icon" = "lucide/list-check" },
    { "Diseño del sistema" = "developers/design.md", "icon" = "lucide/layers" },
    { "Implementación" = "developers/implementation.md", "icon" = "lucide/code" },
    { "Pruebas" = "developers/testing.md", "icon" = "lucide/activity" },
    { "Despliegue" = "developers/deploy.md", "icon" = "lucide/server" },
    { "Mantenimiento" = "developers/maintenance.md", "icon" = "lucide/settings" },
    { "Conclusiones y Futuro" = "developers/last_thoughts.md", "icon" = "lucide/lightbulb" },
  ] },
]

[project.theme]
favicon = "assets/img/favicon.png"
language = "es"
features = [
  "announce.dismiss",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "header.autohide",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.instant.preview",
  "navigation.path",
  "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "deep purple"
accent = "deep purple"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "deep purple"
accent = "deep purple"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[project.theme.icon]
logo = "lucide/cat"
repo = "lucide/github"

[project.extra.analytics]
provider = "google"
property = "G-3ZDQFVCCKL"

[project.extra.analytics.feedback]
title = "¿Te fue útil esta página?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "Esta página fue útil"
data = 1
note = "¡Gracias por tu comentario!"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "Esta página podría mejorarse"
data = 0
note = """
  ¡Gracias por tu comentario! Ayúdanos a mejorar esta página utilizando nuestro <a href="#" target="_blank" rel="noopener">formulario de comentarios</a>.
"""