[project]

site_name = "Lumino Docs"

site_description = "All documentation of Lumino"

site_author = "Carla, Patricia y Jonay"

copyright = """
Copyright &copy; 2026 The Carla, Patricia y Jonay
"""

 nav = [
   { "Inicio" = "index.md", "icon" = "lucide/home"},
   { "Requisitos" = "requirements.md", "icon" = "lucide/wrench"},
   { "Diseño" = "design.md", "icon" = "lucide/wrench"},
   { "Implementación" = "implementation.md", "icon" = "lucide/wrench"},
   { "Pruebas" = "testing.md", "icon" = "lucide/wrench"},
   { "Despliegue" = "deploy.md", "icon" = "lucide/wrench"},
   { "Manuales de Usuario" = "user-manual.md", "icon" = "lucide/wrench"},
   { "Mantenimiento" = "maintenance.md", "icon" = "lucide/wrench"},
   { "Conclusiones y Futuro" = "last_thoughts.md", "icon" = "lucide/wrench"},
]

[project.theme]
favicon = "images/favicon.png"
language = "es"
features = [
    "announce.dismiss",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.instant.preview",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.integrate"
]

[[project.theme.palette]] 
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "deep purple"
accent = "deep purple"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "deep purple"
accent = "deep purple"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[project.theme.icon]
logo = "lucide/cat"
repo = "lucide/github"


